import { AVMS, Broadcaster, Churches, db, Museums, PlatformProvider, Rebroadcaster, TelevisionBroadcaster, User, RegisterSchema } from 'astro:db';

export default async function () {
	await db.insert(User).values([
		{
			id: 0,
			name: 'Hub3r',
			avatar: 'neil-sims.png',
			email: 'neil.sims@flowbite.com',
			country: 'United States',
			status: 'Active'
		},
		{
			id: 1,
			name: 'jacks429',
			avatar: 'neil-sims.png',
			email: 'neil.sims@flowbite.com',
			country: 'United States',
			status: 'Active'
		},
		{
			id: 2,
			name: 'Artem1s',
			avatar: 'neil-sims.png',
			email: 'neil.sims@flowbite.com',
			country: 'Slovakia',
			status: 'Offline'
		}
	]);
	await db.insert(PlatformProvider).values([
		{
			First_name: "John",
			Last_name: "Doe",
			Date_of_Birth: "1990-05-15",
			Nationality: "American",
			Permanent_Residence_Long_Term_Stay: "United States",
			Website: "www.johndoe.com",
			Application_Specification: "Mobile",
			Video_Sharing_Platform: "YouTube"
		},
		{
			First_name: "Emma",
			Last_name: "Smith",
			Date_of_Birth: "1985-09-20",
			Nationality: "British",
			Permanent_Residence_Long_Term_Stay: "United Kingdom",
			Website: "www.emmasmith.com",
			Application_Specification: "Web",
			Video_Sharing_Platform: "Vimeo"
		},
		{
			First_name: "Maria",
			Last_name: "Garcia",
			Date_of_Birth: "1995-03-10",
			Nationality: "Spanish",
			Permanent_Residence_Long_Term_Stay: "Spain",
			Website: "www.mariagarcia.com",
			Application_Specification: "Mobile",
			Video_Sharing_Platform: "Twitch"
		},
	]);
	await db.insert(Rebroadcaster).values([{
		Name: "Global Broadcasting Inc.",
		Identification_Number: "GBI123",
		Headquarters: "New York, USA",
		Legal_Form: "Corporation",
		Method_of_Providing_Rebroadcasting: "Satellite",
		If_Network_or_Telecommunications_Equipment_Cannot_Be_Specified: "N/A",
		Territorial_Scope_Territory_of_Rebroadcasting_Provision: "Worldwide",
		Participants: 500
	},
	{
		Name: "TechStream Solutions",
		Identification_Number: "TS456",
		Headquarters: "London, UK",
		Legal_Form: "LLC",
		Method_of_Providing_Rebroadcasting: "Internet Streaming",
		If_Network_or_Telecommunications_Equipment_Cannot_Be_Specified: "N/A",
		Territorial_Scope_Territory_of_Rebroadcasting_Provision: "European Union",
		Participants: 200
	},
	{
		Name: "Asia Media Group",
		Identification_Number: "AMG789",
		Headquarters: "Tokyo, Japan",
		Legal_Form: "Corporation",
		Method_of_Providing_Rebroadcasting: "Cable TV",
		If_Network_or_Telecommunications_Equipment_Cannot_Be_Specified: "N/A",
		Territorial_Scope_Territory_of_Rebroadcasting_Provision: "Asia-Pacific",
		Participants: 300
	},
	]);
	await db.insert(AVMS).values([
		{
			Name: "ABC Media Group",
			Trade_Name: "ABC",
			First_name: "John",
			Last_name: "Smith",
			Business_Address: "123 Main Street",
			Residence: "New York, USA",
			Telephone_Number: 1234567890,
			Email: "john@example.com",
			Website: "www.abcmediagroup.com",
			Ownership_Structure: "Public Limited Company",
			Ultimate_Beneficial_Owner: "John Smith",
			Competence_of_Regulator: "Federal Communications Commission",
			Jurisdiction_of_SR: "United States",
			Self_Regulatory_Mechanism: "Code of Conduct",
			Self_Regulatory_Body: "Industry Association",
			Authorization_Number: "AVMS123",
			Name_of_AVMS: "ABC TV",
			Specification_of_AVMS_Application: "Television Broadcasting",
			Statement_of_Whether_It_Is_a_Community_Video_Service: "No"
		},
		{
			Name: "TechVision Inc.",
			Trade_Name: "TechVision",
			First_name: "Emma",
			Last_name: "Johnson",
			Business_Address: "456 Elm Street",
			Residence: "London, UK",
			Telephone_Number: 9876543210,
			Email: "emma@example.com",
			Website: "www.techvision.com",
			Ownership_Structure: "Private Limited Company",
			Ultimate_Beneficial_Owner: "Emma Johnson",
			Competence_of_Regulator: "Ofcom",
			Jurisdiction_of_SR: "United Kingdom",
			Self_Regulatory_Mechanism: "Guidelines",
			Self_Regulatory_Body: "Industry Consortium",
			Authorization_Number: "AVMS456",
			Name_of_AVMS: "TechVision TV",
			Specification_of_AVMS_Application: "Online Streaming",
			Statement_of_Whether_It_Is_a_Community_Video_Service: "Yes"
		},
		{
			Name: "MediaHub Asia",
			Trade_Name: "MediaHub",
			First_name: "Michael",
			Last_name: "Chen",
			Business_Address: "789 Oak Avenue",
			Residence: "Tokyo, Japan",
			Telephone_Number: 5555555555,
			Email: "michael@example.com",
			Website: "www.mediahubasia.com",
			Ownership_Structure: "Joint Venture",
			Ultimate_Beneficial_Owner: "Michael Chen",
			Competence_of_Regulator: "Ministry of Communications",
			Jurisdiction_of_SR: "Japan",
			Self_Regulatory_Mechanism: "Voluntary Standards",
			Self_Regulatory_Body: "Industry Association",
			Authorization_Number: "AVMS789",
			Name_of_AVMS: "MediaHub Asia TV",
			Specification_of_AVMS_Application: "Cable Broadcasting",
			Statement_of_Whether_It_Is_a_Community_Video_Service: "No"
		},
	]);
	await db.insert(Broadcaster).values([
		{
			Name: "ABC Broadcasting Corporation",
			Trade_Name: "ABC",
			First_name: "John",
			Last_name: "Smith",
			Business_Address: "123 Main Street",
			Residence: "New York, USA",
			Telephone_Number: 1234567890,
			Email: "john@example.com",
			Website: "www.abcbroadcasting.com",
			Ownership_Structure: "Public Limited Company",
			Ultimate_Beneficial_Owner: "John Smith",
			Competence_of_Regulator: "Federal Communications Commission",
			Jurisdiction_of_SR: "United States",
			Self_Regulatory_Mechanism: "Code of Conduct",
			Self_Regulatory_Body: "Industry Association",
			Authorization_Number: "ABC123",
			Name_of_Program_Service: "ABC News",
			Digital_Reception_Standard: "ATSC",
			Method_of_Public_Transmission: "Terrestrial Broadcasting",
			Is_Local_Broadcasting: true,
			Is_Community_Broadcasting: false,
			Is_a_Monotype_Program_Service: false,
			Is_Broadcast_via_the_Internet: false,
			Broadcast_Language: "English",
			Time_Range: "24/7",
			Clause: "Standard Broadcasting License",
			Allocated_Frequencies: "VHF Band",
			Technical_Parameters_Frequency_List_Number: "ABC-FREQ-001",
			Time_for_Which_the_License_Is_Granted: "10 years",
			Use_of_the_Supplementary_Broadcasting_Service: "No",
			License_Number: 9876
		},
		{
			Name: "TechVision Broadcast Network",
			Trade_Name: "TechVision",
			First_name: "Emma",
			Last_name: "Johnson",
			Business_Address: "456 Elm Street",
			Residence: "London, UK",
			Telephone_Number: 9876543210,
			Email: "emma@example.com",
			Website: "www.techvisionbroadcast.com",
			Ownership_Structure: "Private Limited Company",
			Ultimate_Beneficial_Owner: "Emma Johnson",
			Competence_of_Regulator: "Ofcom",
			Jurisdiction_of_SR: "United Kingdom",
			Self_Regulatory_Mechanism: "Guidelines",
			Self_Regulatory_Body: "Industry Consortium",
			Authorization_Number: "TV456",
			Name_of_Program_Service: "TechVision Tech Talk",
			Digital_Reception_Standard: "DVB-T2",
			Method_of_Public_Transmission: "Satellite Broadcasting",
			Is_Local_Broadcasting: false,
			Is_Community_Broadcasting: false,
			Is_a_Monotype_Program_Service: false,
			Is_Broadcast_via_the_Internet: false,
			Broadcast_Language: "English",
			Time_Range: "Monday to Friday, 8 PM - 10 PM",
			Clause: "Satellite Broadcasting License",
			Allocated_Frequencies: "Ku Band",
			Technical_Parameters_Frequency_List_Number: "TV-FREQ-002",
			Time_for_Which_the_License_Is_Granted: "5 years",
			Use_of_the_Supplementary_Broadcasting_Service: "Yes",
			License_Number: 5432
		},
		{
			Name: "Asia Media Broadcast",
			Trade_Name: "Asia Media",
			First_name: "Michael",
			Last_name: "Chen",
			Business_Address: "789 Oak Avenue",
			Residence: "Tokyo, Japan",
			Telephone_Number: 5555555555,
			Email: "michael@example.com",
			Website: "www.asiamediabroadcast.com",
			Ownership_Structure: "Joint Venture",
			Ultimate_Beneficial_Owner: "Michael Chen",
			Competence_of_Regulator: "Ministry of Communications",
			Jurisdiction_of_SR: "Japan",
			Self_Regulatory_Mechanism: "Voluntary Standards",
			Self_Regulatory_Body: "Industry Association",
			Authorization_Number: "ASIA789",
			Name_of_Program_Service: "Asia News Hour",
			Digital_Reception_Standard: "ISDB-T",
			Method_of_Public_Transmission: "Cable Broadcasting",
			Is_Local_Broadcasting: false,
			Is_Community_Broadcasting: false,
			Is_a_Monotype_Program_Service: false,
			Is_Broadcast_via_the_Internet: false,
			Broadcast_Language: "Japanese",
			Time_Range: "Daily, 6 PM - 8 PM",
			Clause: "Cable Broadcasting License",
			Allocated_Frequencies: "UHF Band",
			Technical_Parameters_Frequency_List_Number: "ASIA-FREQ-003",
			Time_for_Which_the_License_Is_Granted: "7 years",
			Use_of_the_Supplementary_Broadcasting_Service: "No",
			License_Number: 2468
		},
	]);
	await db.insert(TelevisionBroadcaster).values([{
		Broadcaster: "ABC Broadcasting Corporation",
		Name: "ABC News Channel",
		Trade_Name: "ABC",
		First_Name: "John",
		Last_Name: "Smith",
		Address_of_Registered_Office: "123 Main Street",
		Place_of_Business: "New York, USA",
		Residence: "New York, USA",
		Telephone_Number: 1234567890,
		Email: "john@example.com",
		Website: "www.abcbroadcasting.com",
		Ownership_Structure: "Public Limited Company",
		Ultimate_Beneficial_Owner: "John Smith",
		Competence_of_Regulator: "Federal Communications Commission",
		Jurisdiction_of_SR: "United States",
		Self_Regulatory_Mechanism: "Code of Conduct",
		Self_Regulatory_Body: "Industry Association",
		Authorization_Number: 98765,
		Name_of_Program_Service: "ABC News",
		Digital_Reception_Standard: "ATSC",
		Basic_Method_of_Public_Transmission: "Terrestrial Broadcasting",
		Is_Local_Broadcasting: true,
		Community_Broadcasting: false,
		Is_a_Monotype_Program_Service: false,
		Is_Broadcast_via_the_Internet: false,
		Broadcast_Language: "English",
		Time_Range: "24/7",
		Preliminary_Public_Access_to_Major_Events: "Yes",
		Requirements_of_the_Relevant_Decision_on_the_Clause: "Adherence to broadcasting standards"
	},
	{
		Broadcaster: "TechVision Broadcast Network",
		Name: "TechVision Tech Talk",
		Trade_Name: "TechVision",
		First_Name: "Emma",
		Last_Name: "Johnson",
		Address_of_Registered_Office: "456 Elm Street",
		Place_of_Business: "London, UK",
		Residence: "London, UK",
		Telephone_Number: 9876543210,
		Email: "emma@example.com",
		Website: "www.techvisionbroadcast.com",
		Ownership_Structure: "Private Limited Company",
		Ultimate_Beneficial_Owner: "Emma Johnson",
		Competence_of_Regulator: "Ofcom",
		Jurisdiction_of_SR: "United Kingdom",
		Self_Regulatory_Mechanism: "Guidelines",
		Self_Regulatory_Body: "Industry Consortium",
		Authorization_Number: 54321,
		Name_of_Program_Service: "TechVision Tech Talk",
		Digital_Reception_Standard: "DVB-T2",
		Basic_Method_of_Public_Transmission: "Satellite Broadcasting",
		Is_Local_Broadcasting: false,
		Community_Broadcasting: false,
		Is_a_Monotype_Program_Service: false,
		Is_Broadcast_via_the_Internet: false,
		Broadcast_Language: "English",
		Time_Range: "Monday to Friday, 8 PM - 10 PM",
		Preliminary_Public_Access_to_Major_Events: "No",
		Requirements_of_the_Relevant_Decision_on_the_Clause: "Compliance with satellite broadcasting regulations"
	},
	{
		Broadcaster: "Asia Media Broadcast",
		Name: "Asia News Hour",
		Trade_Name: "Asia Media",
		First_Name: "Michael",
		Last_Name: "Chen",
		Address_of_Registered_Office: "789 Oak Avenue",
		Place_of_Business: "Tokyo, Japan",
		Residence: "Tokyo, Japan",
		Telephone_Number: 5555555555,
		Email: "michael@example.com",
		Website: "www.asiamediabroadcast.com",
		Ownership_Structure: "Joint Venture",
		Ultimate_Beneficial_Owner: "Michael Chen",
		Competence_of_Regulator: "Ministry of Communications",
		Jurisdiction_of_SR: "Japan",
		Self_Regulatory_Mechanism: "Voluntary Standards",
		Self_Regulatory_Body: "Industry Association",
		Authorization_Number: 12345,
		Name_of_Program_Service: "Asia News Hour",
		Digital_Reception_Standard: "ISDB-T",
		Basic_Method_of_Public_Transmission: "Cable Broadcasting",
		Is_Local_Broadcasting: false,
		Community_Broadcasting: false,
		Is_a_Monotype_Program_Service: false,
		Is_Broadcast_via_the_Internet: false,
		Broadcast_Language: "Japanese",
		Time_Range: "Daily, 6 PM - 8 PM",
		Preliminary_Public_Access_to_Major_Events: "Yes",
		Requirements_of_the_Relevant_Decision_on_the_Clause: "Compliance with cable broadcasting regulations"
	},
	]);
	await db.insert(Churches).values([{
		ICO: "12345678",
		Date_of_Establishment: "2000-01-01",
		Date_of_Termination: null,
		Form: "Religious Association",
		SKNACE: "12345",
		Name: "Saint Mary's Church",
		Address: "123 Main Street",
		Address_House_Number: 123,
		Address_Postal_Code: 12345,
		Address_Municipality: "Anytown",
		Address_Zip_Code: 54321,
		Address_Post_Office: "Anytown Post Office",
		Church_Founder: "John Doe",
		Registration_Number: 987654,
		Registration_Date: "2000-01-01",
		Statutory_Body: "Board of Trustees",
		Statutory_Body_Name: "Jane",
		Statutory_Body_Surname: "Smith",
		Statutory_Body_Date_of_Birth: "1980-05-10",
		Statutory_Body_Effective_From: "2020-01-01"
	},
	{
		ICO: "87654321",
		Date_of_Establishment: "1995-03-15",
		Date_of_Termination: "2005-03-15",
		Form: "Religious Association",
		SKNACE: "54321",
		Name: "Grace Community Church",
		Address: "456 Elm Street",
		Address_House_Number: 456,
		Address_Postal_Code: 54321,
		Address_Municipality: "Othertown",
		Address_Zip_Code: 12345,
		Address_Post_Office: "Othertown Post Office",
		Church_Founder: "Emma Johnson",
		Registration_Number: 654321,
		Registration_Date: "1995-03-15",
		Statutory_Body: "Church Council",
		Statutory_Body_Name: "Michael",
		Statutory_Body_Surname: "Chen",
		Statutory_Body_Date_of_Birth: "1975-08-20",
		Statutory_Body_Effective_From: "2018-01-01"
	},
	{
		ICO: "56789123",
		Date_of_Establishment: "1980-10-20",
		Date_of_Termination: null,
		Form: "Religious Association",
		SKNACE: "98765",
		Name: "Hope Baptist Church",
		Address: "789 Oak Avenue",
		Address_House_Number: 789,
		Address_Postal_Code: 98765,
		Address_Municipality: "Smalltown",
		Address_Zip_Code: 67890,
		Address_Post_Office: "Smalltown Post Office",
		Church_Founder: "David Williams",
		Registration_Number: 345678,
		Registration_Date: "1980-10-20",
		Statutory_Body: "Church Elders",
		Statutory_Body_Name: "William",
		Statutory_Body_Surname: "Jones",
		Statutory_Body_Date_of_Birth: "1965-04-15",
		Statutory_Body_Effective_From: "2015-01-01"
	}
	]);
	await db.insert(Museums).values([{
		Reg_No: 12345,
		Museum_Name: "National History Museum",
		City: "London",
		Street_Number: 10,
		Street: "Main Street",
		Postal_Code: 12345,
		Phone: 1234567890,
		Fax: 9876543210,
		Email: "info@nationalhistorymuseum.com",
		Website: "www.nationalhistorymuseum.com",
		Business_ID_ICO: 67890,
		Founder_Established_by: "John Smith",
		Legal_Entity_Name: "National History Museum Ltd.",
		Date_of_Registration: "1990-05-15",
		Type: "Natural History"
	},
	{
		Reg_No: 54321,
		Museum_Name: "Louvre Museum",
		City: "Paris",
		Street_Number: 1,
		Street: "Rue de Rivoli",
		Postal_Code: 75001,
		Phone: 1122334455,
		Fax: 5566778899,
		Email: "info@louvremuseum.fr",
		Website: "www.louvre.fr",
		Business_ID_ICO: 98765,
		Founder_Established_by: "Napoleon Bonaparte",
		Legal_Entity_Name: "Louvre Museum",
		Date_of_Registration: "1793-08-10",
		Type: "Art"
	},
	{
		Reg_No: 67890,
		Museum_Name: "Smithsonian Institution",
		City: "Washington D.C.",
		Street_Number: 1000,
		Street: "Constitution Ave NW",
		Postal_Code: 20560,
		Phone: 2026331000,
		Fax: 2026335285,
		Email: "info@si.edu",
		Website: "www.si.edu",
		Business_ID_ICO: 54321,
		Founder_Established_by: "James Smithson",
		Legal_Entity_Name: "Smithsonian Institution",
		Date_of_Registration: "1846-08-10",
		Type: "Various"
	}
	]);
	await db.insert(RegisterSchema).values([
		{
			id: 1,
			Sector: "Museums",
			ExistingRegisters: "Register of Museums and Galleries of the Slovak Republic",
			EntityCount: 118,
			EstimatedCompleteness: 100,
			TotalEntityCount: 118
		},
		{
			id: 2,
			Sector: "Libraries",
			ExistingRegisters: "List of Libraries",
			EntityCount: 5306,
			EstimatedCompleteness: 100,
			TotalEntityCount: 5306
		},
		{
			id: 3,
			Sector: "Monuments",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 4,
			Sector: "Traditional Culture",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 5,
			Sector: "Theater, Dance",
			ExistingRegisters: "Evidence of Theaters and Evidence of Music Institutions",
			EntityCount: 63,
			EstimatedCompleteness: 30.6,
			TotalEntityCount: 63
		},
		{
			id: 7,
			Sector: "Visual Arts",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 8,
			Sector: "Literature",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 9,
			Sector: "Media",
			ExistingRegisters: "Evidence of Periodic Press",
			EntityCount: 108,
			EstimatedCompleteness: 87.2,
			TotalEntityCount: 108
		},
		{
			id: 10,
			Sector: "Audiovisual",
			ExistingRegisters: "Providers of Audiovisual Media Service",
			EntityCount: 348,
			EstimatedCompleteness: 21.1,
			TotalEntityCount: 348
		},
		{
			id: 11,
			Sector: "Gaming Industry",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 12,
			Sector: "Architecture",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 13,
			Sector: "Design",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 14,
			Sector: "Amatuer Artistic Activity",
			ExistingRegisters: "List of ZUČ Groups and Individuals",
			EntityCount: 556,
			EstimatedCompleteness: 100,
			TotalEntityCount: 556
		},
		{
			id: 15,
			Sector: "Education of Professionals in Culture",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 16,
			Sector: "Culture of National Minorities",
			ExistingRegisters: "Evidence of Cultural Organizations of National Minorities",
			EntityCount: 282,
			EstimatedCompleteness: 26,
			TotalEntityCount: 282
		},
		{
			id: 17,
			Sector: "Cultures of Disadvantaged Groups",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 18,
			Sector: "State Language and Communication",
			ExistingRegisters: "N/A",
			EntityCount: 0,
			EstimatedCompleteness: 0,
			TotalEntityCount: 0
		},
		{
			id: 19,
			Sector: "Church",
			ExistingRegisters: "Register of Churches and Religious Societies",
			EntityCount: 2961,
			EstimatedCompleteness: 100,
			TotalEntityCount: 2961
		}
	]);
}
